#    ______________    ____  _____ __  __________ 
#   / ___/_  __/   |  / __ \/ ___// / / /  _/ __ \
#   \__ \ / / / /| | / /_/ /\__ \/ /_/ // // /_/ /
#  ___/ // / / ___ |/ _, _/___/ / __  // // ____/ 
# /____//_/ /_/  |_/_/ |_|/____/_/ /_/___/_/      
#
# https://github.com/jorgeloopzz

# Inserts a blank line between shell prompts
add_newline = true

# Standard configuration
[character]
success_symbol = "[➜](bold green)" 
error_symbol = "[✗](bold red)"
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[󰑓](bold yellow)'
vimcmd_visual_symbol = '[](bold yellow)'

[username]
format = '[ $user](bold blue) in '
disabled = false
show_always = true

# Programming languages configuration
[python]
symbol = " "

[nodejs]
symbol = " "
detect_files = ['package.json']
detect_folders = ["node_modules"]
detect_extensions = [""]

[rust]
symbol = "󱘗 "
detect_files = ['Cargo.toml']
detect_extensions = ['rs']

[java]
symbol = "󰬷 "
detect_files = ['']
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc']

[c]
symbol = " "
detect_extensions = ['c', 'h']

