#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
redshift -P -O 3200 &
picom --config ~/.config/picom/picom.conf --experimental-backends &
nm-applet &
udiskie -t &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12
bspc config focused_border_color "#ff0000"
bspc config normal_border_color "#8b0000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

