#! /bin/sh

# Programs to run when a session is started
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI1 --mode 1920x1080 --rate 60.00 --right-of eDP1 &
~/.config/polybar/launch.sh &
nitrogen --restore &
redshift -P -O 3200 &
picom --config ~/.config/picom/picom.conf --experimental-backends &
dunst -conf /home/jorge/.config/dunst/bspwmrc &
nm-applet &
udiskie &

### WORKSPACES ###
bspc monitor -d I II III IV V VI VII VIII IX X

### GAPS ###
bspc config window_gap          12

### BORDERS ###
bspc config border_width         1
bspc config focused_border_color "#ff6666"
bspc config normal_border_color "#8b0000"

### WINDOW CONFIG ###
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Open apllications in certain workspaces
bspc rule -a LibreWolf desktop='^1' follow=on
bspc rule -a Tor Browser desktop='^1' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a code-oss desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a discord desktop='^5' follow=on
bspc rule -a nuclear desktop='^6' follow=on
bspc rule -a TelegramDesktop desktop='^7' follow=on

