#! /bin/sh

# Programs to run when a session is started
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf --experimental-backends &
dunst -conf /home/jorge/.config/dunst/bspwmrc &

### WORKSPACES ###
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

### GAPS ###
bspc config window_gap          12

### BORDERS ###
bspc config border_width         1
bspc config focused_border_color "#ff6666"
bspc config normal_border_color "#8b0000"

### WINDOW CONFIG ###
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Open apllications in certain workspaces
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a VSCodium desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^6' follow=on

# Floatin window
bspc rule -a Tk follow=on state=floating

